export const issueSearchMock = {
    'total_count': 2,
    'incomplete_results': false,
    'items': [
        {
            'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2',
            'repository_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard',
            'labels_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2/labels{/name}',
            'comments_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2/comments',
            'events_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2/events',
            'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2',
            'id': 395054012,
            'node_id': 'MDExOlB1bGxSZXF1ZXN0MjQxNjE2MDY5',
            'number': 2,
            'title': 'Test PR #2 - Team Mention',
            'user': {
                'login': 'chodges15',
                'id': 24880218,
                'node_id': 'MDQ6VXNlcjI0ODgwMjE4',
                'avatar_url': 'https://avatars0.githubusercontent.com/u/24880218?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/chodges15',
                'html_url': 'https://github.com/chodges15',
                'followers_url': 'https://api.github.com/users/chodges15/followers',
                'following_url': 'https://api.github.com/users/chodges15/following{/other_user}',
                'gists_url': 'https://api.github.com/users/chodges15/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/chodges15/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/chodges15/subscriptions',
                'organizations_url': 'https://api.github.com/users/chodges15/orgs',
                'repos_url': 'https://api.github.com/users/chodges15/repos',
                'events_url': 'https://api.github.com/users/chodges15/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/chodges15/received_events',
                'type': 'User',
                'site_admin': false
            },
            'labels': [],
            'state': 'open',
            'locked': false,
            'assignee': null,
            'assignees': [],
            'milestone': null,
            'comments': 0,
            'created_at': '2019-01-01T04:13:33Z',
            'updated_at': '2019-01-01T04:13:33Z',
            'closed_at': null,
            'author_association': 'MEMBER',
            'pull_request': {
                'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/pulls/2',
                'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2',
                'diff_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2.diff',
                'patch_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2.patch'
            },
            'body': '@LeanAgileSoftware/test ',
            'score': 1
        },
        {
            'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1',
            'repository_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard',
            'labels_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1/labels{/name}',
            'comments_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1/comments',
            'events_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1/events',
            'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1',
            'id': 395053354,
            'node_id': 'MDExOlB1bGxSZXF1ZXN0MjQxNjE1Njg0',
            'number': 1,
            'title': 'Test PR #1 - Team Mention',
            'user': {
                'login': 'chodges15',
                'id': 24880218,
                'node_id': 'MDQ6VXNlcjI0ODgwMjE4',
                'avatar_url': 'https://avatars0.githubusercontent.com/u/24880218?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/chodges15',
                'html_url': 'https://github.com/chodges15',
                'followers_url': 'https://api.github.com/users/chodges15/followers',
                'following_url': 'https://api.github.com/users/chodges15/following{/other_user}',
                'gists_url': 'https://api.github.com/users/chodges15/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/chodges15/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/chodges15/subscriptions',
                'organizations_url': 'https://api.github.com/users/chodges15/orgs',
                'repos_url': 'https://api.github.com/users/chodges15/repos',
                'events_url': 'https://api.github.com/users/chodges15/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/chodges15/received_events',
                'type': 'User',
                'site_admin': false
            },
            'labels': [],
            'state': 'open',
            'locked': false,
            'assignee': null,
            'assignees': [],
            'milestone': null,
            'comments': 0,
            'created_at': '2019-01-01T03:53:00Z',
            'updated_at': '2019-01-01T03:53:00Z',
            'closed_at': null,
            'author_association': 'MEMBER',
            'pull_request': {
                'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/pulls/1',
                'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1',
                'diff_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1.diff',
                'patch_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1.patch'
            },
            'body': '@LeanAgileSoftware/test ',
            'score': 1
        }
    ]
};
